# Generated by Django 5.0.7 on 2024-09-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='plans',
            old_name='title',
            new_name='heading',
        ),
    ]
