# Generated by Django 5.0.7 on 2024-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_title_news_heading_rename_title_plans_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plans/'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
